name: build_and_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust toolchain
      run: rustup update --no-self-update stable
    - name: Clippy
      run: cargo clippy
    - name: Test
      run: cargo test
    - name: Build
      run: cargo build --release
